name: 'Trilogy Engineering Standards'
description: 'Ensures a repository complies with the new ShipEveryMerge Engineering standard'
inputs:
  repository:
    description: 'Repository name with owner. For example, trilogy-group/sococo'
    default: ${{ github.repository }}
    required: false
  branch:
    description: 'The full name (e.g. refs/heads/branch) of the target branch'
    default: ${{ github.head_ref }}
    required: false
  repair:
    description: 'Repair issues that we can'
    default: "false"
    required: false
runs:
  using: node12
  main: dist/index.js
