name: Continuous flow

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:

      - name: Setup repo
        uses: actions/checkout@v2
      
      - name: Get template
        uses: actions/checkout@v2
        with:
          repository: trilogy-group/eng-template
          token: ${{ secrets.ENG_STD_TOKEN }}
          path: template

      - name: Release
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          rm -rf template/.git
          bin/release.sh
