name: Release GitHub Action

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:

      - name: Setup repo
        uses: actions/checkout@v2

      - name: Release
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          bin/release.sh
